backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
i18n:
  structure: multiple_folders
  locales: [en, it]
  default_locale: en
collections:
  - name: settings
    label: 'Settings'
    files:
      - label: 'General'
        name: 'general'
        file: 'content/settings/general.yml'
        fields:
          - label: Brand name
            name: brandName
            widget: string

          - label: Logo
            name: logo
            widget: image
            required: false

          - label: Base page title
            name: basePageTitle
            widget: string

      - label: 'Navigation'
        name: 'navigation'
        file: 'content/settings/navigation.yml'
        fields:
          - label: 'Header navigation'
            name: header
            label_singular: 'Header link'
            widget: list
            fields:
              - label: Label
                name: Label
                widget: string
                i18n: true

              - label: Page
                name: page
                widget: relation
                collection: pages
                required: false
                value_field: '{{slug}}'
                search_fields: ['name']

              - label: Link
                name: href
                widget: string
                required: false

          - label: 'Footer navigation'
            name: footer
            label_singular: 'Footer link'
            widget: list
            fields:
              - label: Label
                name: Label
                widget: string
                i18n: true

              - label: Page
                name: page
                widget: relation
                collection: pages
                required: false
                value_field: '{{slug}}'
                search_fields: ['name']

              - label: Link
                name: href
                widget: string
                required: false

  - name: pages
    label: 'Pages'
    label_singular: 'Page'
    i18n: true
    folder: content/pages
    identifier_field: name
    create: true
    fields:
      - { label: 'Name', name: name, widget: string }
      - { label: 'Title', name: title, widget: string, i18n: true }
      - { label: 'Publish Date', name: created, widget: datetime }
      - { label: 'Body', name: body, widget: markdown, i18n: true }
