backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
i18n:
  structure: multiple_folders
  locales: [en, it]
  default_locale: en
collections:
  - name: pages
    label: 'Pages'
    label_singular: 'Page'
    i18n: true
    folder: content/pages
    create: true
    fields:
      - { label: 'Title', name: title, widget: string, i18n: true }
      - { label: 'Publish Date', name: date, widget: datetime }
      - { label: 'Body', name: body, widget: markdown }
